Movie.destroy_all
Movie.create!([
    {name:"A Space Odyssey", description:"Both Interstellar and Gravity took us out of this world, but the reputation of Stanley Kubricks classic – now re-released – is safe. Its not that 2001: A Space Odyssey doesnt look dated – it does, a bit – but it remains as intelligent and provocative as ever, bearing years of conceptual dreaming. Until todays equivalent of novelist Arthur C Clarke commits a hefty chunk of time to envisioning the beginning of human civilisation, as well as the far future, there will be no new film to supplant it.
    Though it was showered with praise for its technical achievements, 2001 lingers more potently in the mind as a tall, black riddle: where are the new bones, the new tools, that will take us higher? Douglas Rains clammy voice work as Hal 9000, the murderous machine, remains one of Kubricks snazziest pieces of direction."},
    {name:"The Godfather", description:"An everyday story of Mafia folk, incorporating a severed horses head in the bed and a number of heartwarming family occasions, as well as pointers on how not to behave in your local trattoria (i.e. blasting the brains of your co-diners out all over their fettuccini)"},
    {name:"Citizen Kane", description:"The source book of Orson Welles, and still a marvellous movie. Thematically less resonant than some of Welles later meditations on the nature of power, perhaps, but still absolutely riveting as an investigation of a citizen"},
    {name:"Jeanne Dielman, 23 Quai du Commerce, 1080 Bruxelles", description:"Chantal Akermans feature is one of the few 'feminist' movies that's as interesting aesthetically as politically. It covers three days in the life of a bourgeois widow who supports herself and her somewhat moronic son by taking in a gentleman caller each afternoon."},
    {name:"Time Out says", description:"Chantal Akerman's feature is one of the few 'feminist' movies that's as interesting aesthetically as politically. It covers three days in the life of a bourgeois widow who supports herself and her somewhat moronic son by taking in a 'gentleman caller' each afternoon. Much of the film simply chronicles her ritualised routine, but does it in an ultra-minimal, precise style that emphasises the artifice of the whole thing...and gradually the artifice (coupled with the fact that Delphine Seyrig plays the woman) shifts the plot into melodrama, so that the film becomes a bourgeois tragedy."},
    {name:"La Dolce Vita", description:"The flying statue of Jesus, hovering over Rome via helicopter; Anita Ekberg, voluptuously traipsing around the Trevi Fountain; that climactic metaphor of a bloated, beached sea creature, staring dead-eyed at Marcello Mastroianni's fatigued urban Candide. It's so easy to reduce Federico Fellini's three-ring satire of the Euro-chic good life to iconic scenes, or to accept the movie simply as a canonized classic (of course it's great; they teach it in college courses!), that you can forget what a damning indictment of This Mondo Modern World it really is.

    Yes, Film Forum's two-week revival of il maestro's groundbreaking work should be considered mandatory attendance anyway, given that this new 35mm restoration is gorgeous; the movie's aristocratic filth has never looked so pristine. But the real reason to wallow once more in its parade of faux Madonnas and real whores, rich junkies and jerkwads, parasitic paparazzi (a term the film coined), dim-bulb starlets, drunken louts and the lowest of the low---that'd be journalists---is to recognize, with stunning clarity, the morally bankrupt, media-fried here and now. Historians can laud it as the transitional pause before the director fully abandoned any neorealistic flourishes and dove into the psycho-personal surrealism known as the Fellini-esque. Yet everyone else will simply admire, in slack-jawed stupor, the way this 51-year-old time capsule thoroughly predicts the era of TMZ, Paris Hilton and celebutante overload. Everything has changed, and nothing has changed. How sour it still is."},
    {name:"In the Mood for Love", description:"Wong's paean to the agony'n ecstasy of buttoned-up emotions is a kind-of sequel to Days of Being Wild, shaped and scored as a valse triste. In Hong Kong, 1962, Mr Chow (Leung) and Mrs Chan (Cheung) are neighbours who discover that their spouses are having an affair. He finds excuses to spend time with her, apparently intending to jilt her. Then they fall in love, but (aside from one reckless moment in a hotel) repress their feelings. He runs away to work as a journalist in Singapore; in 1966, covering De Gaulle's state visit to Cambodia, he's in Angkor Wat trying to unburden himself of the secret which overwhelms his life... Every charged frame of the film pulses with the central contradiction between repression and emotional abandon; the formalism and sensuality are inextricable. Career-best performances from both leads, Leung having a Cannes 'Best Actor' prize to show for his."},
    {name:"There Will Be Blood", description:"We begin down a hole. It’s 1898 in the Southern Californian desert and Daniel Plainview (Daniel Day-Lewis) is a lithe, daddy-long-legs of a man, a lone-gun silver prospector whose tools, as he scratches around in the dark, are a pickaxe, a rope, some dynamite and sheer will. The scene, like many in the film, is gruelling, elemental, horrific even.

    He falls, breaks his leg and gains a limp that will stay with him for the rest of this bold, epic film. We hop forward to 1902, and Plainview is digging again, only now he’s on the hunt for something else: oil. He strikes black and brandishes his filthy hands to his accomplices. The dirt under his nails is a badge of honour, and one never to be removed; he wears it years later, even when he’s moping around a mansion, his mind driven loopy by success and paranoia.
    
    Another hop and it’s 1911, and we reach the meat of the movie. A smarter Plainview, a fedora on his brow, is in the shadows of a meeting of folk in Little Boston, California on whose land he wants to dig. ‘I’m an oil man…’ he implores, the first noise we hear from his mouth, not a word wasted, barely a breath not invested in his success. His voice is simple but mellifluous, its stresses and dips unusual but alluring. It’s the first hint in this long, odd and stunning film that this character – this wicked creation, this symbol of a nation, this quiet monster – will lodge in your psyche long after the movie cuts dead on an ending that’s strange and sudden, irritating and pleasing.
    
    On one level, Plainview is a pure businessman – ruthless, self-centred, adaptable. On another, he’s a mystery – sexless, rootless, unfathomable, silent. The questions roll off the screen. Does he care for his adopted son, HW (Dillon Freasier) or does he see him only as a useful face to have around during negotiations? Are we meant to root for Plainview’s individualist tendencies against the expansion of the Standard and Union oil companies? No – as soon as the film hints this is going to be the tale of an underdog, Plainview does something awful. Faceless, corporate behaviour begins to look benign. On yet another level, Plainview reflects, then and now, the power of the church; it’s a local pastor, Eli Sunday (a wily Paul Dano) who leads him to the loot. It’s the same pastor whose pockets he must line and religion he must embrace."},
    {name:"Singin' in the Rain", description:"Is there a film clip more often shown than the title number of this most astoundingly popular musical? The rest of the movie is great too. It shouldn't be. There never was a masterpiece created from such a mishmash of elements: Arthur Freed's favourites among his own songs from back in the '20s and '30s, along with a new number, 'Make 'Em Laugh', which is a straight rip-off from Cole Porter's 'Be A Clown'; the barely blooded Debbie Reynolds pitched into the deep end with tyrannical perfectionist Kelly; choreography very nearly improvised because of pressures of time; and Kelly filming his greatest number with a heavy cold. Somehow it all comes together. The 'Broadway Melody' ballet is Kelly's least pretentious, Jean Hagen and Donald O'Connor are very funny, and the Comden/Green script is a loving-care job. If you've never seen it and don't, you're bonkers."},

])
